version: "3"
services:
  # nginx 配置
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/conf.d:/etc/nginx/conf.d/:ro
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/:/var/log/dnmp/:rw
    networks:
      # - net-php
      - net-lnmp
  
  # php-fpm 配置 
  php:
    build: ./php/php72/
    ports:
      - "9502:9502"
    expose:
      - "9000"
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/:/var/log/dnmp/:rw
    networks:
      - net-lnmp
  
  # mysql配置
  mysql:
    image: mysql:8.0
    # restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./data:/var/lib/mysql:rw
    networks:
      - net-lnmp
    environment:
      MYSQL_ROOT_PASSWORD: "123456"

  redis:
    image: redis:4.0
    networks:
      - net-lnmp
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data:rw

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    networks:
      - net-lnmp
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306

# 网络配置
networks:
  net-lnmp:
    driver: bridge